packages:
  - "packages/*"
  - "apps/*"
allowBuilds:
  bufferutil: false
  utf-8-validate: false
  esbuild: true
  sharp: true
  bigint-buffer: false
minimumReleaseAgeExclude:
  - '@hono/node-server@2.1.3'
  - hono@4.13.11
