/**
 * Copies the Anchor IDLs and generated types from target/ into packages/shared.
 *
 * Run after `anchor idl build` for both programs:
 *   anchor idl build -p agent_wallet -o target/idl/agent_wallet.json -t target/types/agent_wallet.ts
 *   anchor idl build -p settlement -o target/idl/settlement.json -t target/types/settlement.ts
 *   pnpm --filter @turnstile/shared exec tsx src/cli/sync-idl.ts
 */
import { copyFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const PROGRAMS = [
  { file: "agent_wallet", constName: "agentWalletIdl" },
  { file: "settlement", constName: "settlementIdl" },
] as const;

function repoRoot(): string {
  let dir = dirname(fileURLToPath(import.meta.url));
  for (;;) {
    if (existsSync(join(dir, "pnpm-workspace.yaml"))) return dir;
    const parent = dirname(dir);
    if (parent === dir) throw new Error("Could not find the repo root above this script.");
    dir = parent;
  }
}

export function syncIdl(): string[] {
  const root = repoRoot();
  const shared = join(root, "packages/shared");
  const written: string[] = [];
  const consts: string[] = [];
  for (const p of PROGRAMS) {
    const idlPath = join(root, "target/idl", `${p.file}.json`);
    const typesPath = join(root, "target/types", `${p.file}.ts`);
    if (!existsSync(idlPath) || !existsSync(typesPath)) {
      throw new Error(`${idlPath} or ${typesPath} is missing. Run anchor idl build first.`);
    }
    const idlOut = join(shared, "idl", `${p.file}.json`);
    copyFileSync(idlPath, idlOut);
    const typesOut = join(shared, "src/programs", `${p.file}.ts`);
    copyFileSync(typesPath, typesOut);
    written.push(idlOut, typesOut);
    const json = JSON.stringify(JSON.parse(readFileSync(idlPath, "utf8")), null, 2);
    consts.push(`export const ${p.constName} = ${json} as const;`);
  }
  const idlTs = join(shared, "src/programs/idl.ts");
  writeFileSync(
    idlTs,
    `// Generated by src/cli/sync-idl.ts from target/idl. Do not edit by hand.\n\n${consts.join("\n\n")}\n`,
  );
  written.push(idlTs);
  return written;
}

if (process.argv[1] !== undefined && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  for (const path of syncIdl()) process.stdout.write(`wrote ${path}\n`);
}
