// Generated by src/cli/sync-idl.ts from target/idl. Do not edit by hand.

export const agentWalletIdl = {
  address: "7onzUVc1HGc9oBDUspBdP8dz1QW6uXrSdBn4NH6aiLb",
  metadata: {
    name: "agent_wallet",
    version: "0.1.0",
    spec: "0.1.0",
    description: "Turnstile agent wallet with an on-chain spending policy",
  },
  instructions: [
    {
      name: "add_session_key",
      docs: [
        "Adds a session key. A full list reuses the first slot held by a revoked or expired key.",
      ],
      discriminator: [48, 71, 165, 97, 37, 22, 181, 59],
      accounts: [
        {
          name: "owner",
          signer: true,
          relations: ["agent_wallet"],
        },
        {
          name: "agent_wallet",
          writable: true,
        },
      ],
      args: [
        {
          name: "key",
          type: "pubkey",
        },
        {
          name: "expires_at",
          type: "i64",
        },
      ],
    },
    {
      name: "close_wallet",
      docs: ["Closes an empty vault and the wallet. Rent from both goes back to the owner."],
      discriminator: [35, 212, 234, 224, 244, 208, 31, 204],
      accounts: [
        {
          name: "owner",
          writable: true,
          signer: true,
          relations: ["agent_wallet"],
        },
        {
          name: "agent_wallet",
          writable: true,
        },
        {
          name: "vault",
          writable: true,
          relations: ["agent_wallet"],
        },
        {
          name: "token_program",
          address: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
        },
      ],
      args: [],
    },
    {
      name: "create_wallet",
      docs: [
        "Creates the agent wallet PDA and its vault for `mint`, with one session key and caps.",
        "The allow-list starts empty, which allows nothing until the owner sets it.",
      ],
      discriminator: [82, 172, 128, 18, 161, 207, 88, 63],
      accounts: [
        {
          name: "owner",
          writable: true,
          signer: true,
        },
        {
          name: "agent_wallet",
          writable: true,
          pda: {
            seeds: [
              {
                kind: "const",
                value: [97, 103, 101, 110, 116, 95, 119, 97, 108, 108, 101, 116],
              },
              {
                kind: "account",
                path: "owner",
              },
              {
                kind: "arg",
                path: "id",
              },
            ],
          },
        },
        {
          name: "mint",
        },
        {
          name: "vault",
          writable: true,
          pda: {
            seeds: [
              {
                kind: "const",
                value: [118, 97, 117, 108, 116],
              },
              {
                kind: "account",
                path: "agent_wallet",
              },
            ],
          },
        },
        {
          name: "token_program",
          address: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
        },
        {
          name: "system_program",
          address: "11111111111111111111111111111111",
        },
      ],
      args: [
        {
          name: "id",
          type: "u64",
        },
        {
          name: "per_call_cap",
          type: "u64",
        },
        {
          name: "daily_cap",
          type: "u64",
        },
        {
          name: "session_key",
          type: "pubkey",
        },
        {
          name: "session_expires_at",
          type: "i64",
        },
      ],
    },
    {
      name: "debit",
      docs: [
        "Pays `amount` from the vault to `recipient_token` after the full policy check.",
        "Callable only through CPI signed by the settlement program's `settlement_authority`.",
      ],
      discriminator: [144, 252, 105, 115, 174, 111, 100, 65],
      accounts: [
        {
          name: "settlement_authority",
          docs: ["Any other caller gets `UnauthorizedCaller`."],
          signer: true,
          address: "AchLyVbEk5nXx2K73LB43wvBCqY4V4xyei9bTwSrS5Tz",
        },
        {
          name: "agent_wallet",
          writable: true,
        },
        {
          name: "vault",
          writable: true,
          relations: ["agent_wallet"],
        },
        {
          name: "recipient_token",
          writable: true,
        },
        {
          name: "token_program",
          address: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
        },
      ],
      args: [
        {
          name: "session_key",
          type: "pubkey",
        },
        {
          name: "amount",
          type: "u64",
        },
        {
          name: "resource_id",
          type: {
            array: ["u8", 32],
          },
        },
      ],
    },
    {
      name: "deposit",
      docs: ["Moves `amount` from an owner token account into the vault."],
      discriminator: [242, 35, 198, 137, 82, 225, 242, 182],
      accounts: [
        {
          name: "owner",
          signer: true,
          relations: ["agent_wallet"],
        },
        {
          name: "agent_wallet",
        },
        {
          name: "vault",
          writable: true,
          relations: ["agent_wallet"],
        },
        {
          name: "owner_token",
          writable: true,
        },
        {
          name: "token_program",
          address: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
        },
      ],
      args: [
        {
          name: "amount",
          type: "u64",
        },
      ],
    },
    {
      name: "revoke_session_key",
      docs: [
        "Revokes a session key. A revoked key cannot authorize a payment while it stays revoked.",
        "Re-adding the same key later revives any of its unexpired, unsettled authorizations, so rotate",
        "to a new key instead.",
      ],
      discriminator: [81, 192, 32, 110, 104, 116, 144, 151],
      accounts: [
        {
          name: "owner",
          signer: true,
          relations: ["agent_wallet"],
        },
        {
          name: "agent_wallet",
          writable: true,
        },
      ],
      args: [
        {
          name: "key",
          type: "pubkey",
        },
      ],
    },
    {
      name: "rolling_spend",
      docs: ["Returns the spend that counts toward the daily cap right now, as u64 return data."],
      discriminator: [245, 14, 199, 168, 40, 216, 170, 67],
      accounts: [
        {
          name: "agent_wallet",
        },
      ],
      args: [],
      returns: "u64",
    },
    {
      name: "update_policy",
      docs: ["Replaces the caps and the allow-list in one step."],
      discriminator: [212, 245, 246, 7, 163, 151, 18, 57],
      accounts: [
        {
          name: "owner",
          signer: true,
          relations: ["agent_wallet"],
        },
        {
          name: "agent_wallet",
          writable: true,
        },
      ],
      args: [
        {
          name: "per_call_cap",
          type: "u64",
        },
        {
          name: "daily_cap",
          type: "u64",
        },
        {
          name: "allow_list",
          type: {
            vec: {
              defined: {
                name: "AllowListEntry",
              },
            },
          },
        },
      ],
    },
    {
      name: "withdraw",
      docs: ["Moves `amount` from the vault to a token account the owner holds."],
      discriminator: [183, 18, 70, 156, 148, 109, 161, 34],
      accounts: [
        {
          name: "owner",
          signer: true,
          relations: ["agent_wallet"],
        },
        {
          name: "agent_wallet",
        },
        {
          name: "vault",
          writable: true,
          relations: ["agent_wallet"],
        },
        {
          name: "owner_token",
          writable: true,
        },
        {
          name: "token_program",
          address: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
        },
      ],
      args: [
        {
          name: "amount",
          type: "u64",
        },
      ],
    },
  ],
  accounts: [
    {
      name: "AgentWallet",
      discriminator: [127, 35, 180, 143, 201, 1, 100, 50],
    },
  ],
  errors: [
    {
      code: 6000,
      name: "SessionKeyNotFound",
      msg: "This session key is not registered on the agent wallet. Add it with add_session_key first",
    },
    {
      code: 6001,
      name: "SessionKeyRevoked",
      msg: "This session key was revoked. Sign with an active session key",
    },
    {
      code: 6002,
      name: "SessionKeyExpired",
      msg: "This session key has expired. Ask the owner to add a new session key",
    },
    {
      code: 6003,
      name: "PerCallCapExceeded",
      msg: "The amount is above the per-call cap. Pay less or ask the owner to raise the cap",
    },
    {
      code: 6004,
      name: "DailyCapExceeded",
      msg: "The payment would take the last 24 hours above the daily cap. Wait for older spend to age out or raise the cap",
    },
    {
      code: 6005,
      name: "ResourceNotAllowed",
      msg: "This resource and recipient pair is not on the allow-list. Ask the owner to add it",
    },
    {
      code: 6006,
      name: "UnauthorizedCaller",
      msg: "The caller is not allowed to run this instruction. Use the wallet owner or the settlement program",
    },
    {
      code: 6007,
      name: "InsufficientFunds",
      msg: "The vault does not hold enough tokens. Deposit more before paying or withdrawing",
    },
    {
      code: 6008,
      name: "ZeroAmount",
      msg: "The amount must be above zero",
    },
    {
      code: 6009,
      name: "InvalidPolicy",
      msg: "The per-call cap must not exceed the daily cap and expiry times must not be negative",
    },
    {
      code: 6010,
      name: "TooManySessionKeys",
      msg: "The wallet already holds 4 usable session keys. Revoke one before adding another",
    },
    {
      code: 6011,
      name: "AllowListTooLong",
      msg: "The allow-list can hold at most 16 entries",
    },
    {
      code: 6012,
      name: "DuplicateSessionKey",
      msg: "This session key is already on the wallet",
    },
    {
      code: 6013,
      name: "VaultNotEmpty",
      msg: "The vault still holds tokens. Withdraw everything before closing the wallet",
    },
    {
      code: 6014,
      name: "MintMismatch",
      msg: "The token account uses a different mint than the agent wallet",
    },
    {
      code: 6015,
      name: "RecipientMismatch",
      msg: "The destination token account belongs to the wrong owner",
    },
    {
      code: 6016,
      name: "AccountMismatch",
      msg: "An account does not match the agent wallet. Pass the wallet's own vault",
    },
    {
      code: 6017,
      name: "ArithmeticOverflow",
      msg: "A counter would overflow. The wallet cannot record this payment",
    },
  ],
  types: [
    {
      name: "AgentWallet",
      type: {
        kind: "struct",
        fields: [
          {
            name: "owner",
            type: "pubkey",
          },
          {
            name: "id",
            type: "u64",
          },
          {
            name: "mint",
            type: "pubkey",
          },
          {
            name: "vault",
            type: "pubkey",
          },
          {
            name: "bump",
            type: "u8",
          },
          {
            name: "vault_bump",
            type: "u8",
          },
          {
            name: "created_at",
            type: "i64",
          },
          {
            name: "per_call_cap",
            type: "u64",
          },
          {
            name: "daily_cap",
            type: "u64",
          },
          {
            name: "session_keys",
            type: {
              vec: {
                defined: {
                  name: "SessionKey",
                },
              },
            },
          },
          {
            name: "allow_list",
            type: {
              vec: {
                defined: {
                  name: "AllowListEntry",
                },
              },
            },
          },
          {
            name: "spend_buckets",
            docs: ["Ring of 97 buckets. The slot for bucket index `i` is `i mod 97`."],
            type: {
              vec: {
                defined: {
                  name: "SpendBucket",
                },
              },
            },
          },
          {
            name: "total_spent",
            type: "u64",
          },
          {
            name: "settlement_count",
            type: "u64",
          },
        ],
      },
    },
    {
      name: "AllowListEntry",
      type: {
        kind: "struct",
        fields: [
          {
            name: "resource_id",
            type: {
              array: ["u8", 32],
            },
          },
          {
            name: "recipient",
            docs: ["Owner of the recipient token account."],
            type: "pubkey",
          },
        ],
      },
    },
    {
      name: "SessionKey",
      type: {
        kind: "struct",
        fields: [
          {
            name: "key",
            type: "pubkey",
          },
          {
            name: "expires_at",
            docs: ["Unix seconds. 0 means no expiry."],
            type: "i64",
          },
          {
            name: "active",
            type: "bool",
          },
        ],
      },
    },
    {
      name: "SpendBucket",
      type: {
        kind: "struct",
        fields: [
          {
            name: "index",
            docs: ["`floor(unix_timestamp / 900)`."],
            type: "i64",
          },
          {
            name: "amount",
            type: "u64",
          },
        ],
      },
    },
  ],
  constants: [
    {
      name: "SEED_AGENT_WALLET",
      type: "bytes",
      value: "[97, 103, 101, 110, 116, 95, 119, 97, 108, 108, 101, 116]",
    },
    {
      name: "SEED_SETTLEMENT_AUTHORITY",
      type: "bytes",
      value:
        "[115, 101, 116, 116, 108, 101, 109, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121]",
    },
    {
      name: "SEED_VAULT",
      type: "bytes",
      value: "[118, 97, 117, 108, 116]",
    },
  ],
} as const;

export const settlementIdl = {
  address: "6FrY43zorjSv8wCuarPL3z8ZnyBTyyC86xRjBqgu1K9z",
  metadata: {
    name: "settlement",
    version: "0.1.0",
    spec: "0.1.0",
    description: "Turnstile settlement of signed payment authorizations",
  },
  instructions: [
    {
      name: "close_receipt",
      docs: [
        "Closes a receipt and returns its rent to the fee payer that paid it. Allowed only once",
        "`RECEIPT_RETENTION_SECONDS` have passed since the authorization expired. `settle` refuses",
        "an expired authorization before it looks at the receipt, so a closed receipt never lets",
        "its nonce settle again.",
      ],
      discriminator: [126, 254, 244, 203, 124, 164, 134, 89],
      accounts: [
        {
          name: "receipt",
          writable: true,
          pda: {
            seeds: [
              {
                kind: "const",
                value: [114, 101, 99, 101, 105, 112, 116],
              },
              {
                kind: "account",
                path: "receipt.agent_wallet",
                account: "Receipt",
              },
              {
                kind: "account",
                path: "receipt.nonce",
                account: "Receipt",
              },
            ],
          },
        },
        {
          name: "fee_payer",
          docs: ["The fee payer that paid the receipt rent. It signs and receives the lamports."],
          writable: true,
          signer: true,
          relations: ["receipt"],
        },
      ],
      args: [],
    },
    {
      name: "settle",
      discriminator: [175, 42, 185, 87, 144, 131, 102, 212],
      accounts: [
        {
          name: "fee_payer",
          docs: ["Pays the transaction fee and the receipt rent. Has no authority over any funds."],
          writable: true,
          signer: true,
        },
        {
          name: "settlement_authority",
          pda: {
            seeds: [
              {
                kind: "const",
                value: [
                  115, 101, 116, 116, 108, 101, 109, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114,
                  105, 116, 121,
                ],
              },
            ],
          },
        },
        {
          name: "agent_wallet",
          writable: true,
        },
        {
          name: "vault",
          writable: true,
        },
        {
          name: "recipient_token",
          writable: true,
        },
        {
          name: "receipt",
          docs: ["creates it otherwise."],
          writable: true,
          pda: {
            seeds: [
              {
                kind: "const",
                value: [114, 101, 99, 101, 105, 112, 116],
              },
              {
                kind: "arg",
                path: "authorization.agent_wallet",
              },
              {
                kind: "arg",
                path: "authorization.nonce",
              },
            ],
          },
        },
        {
          name: "instructions",
          address: "Sysvar1nstructions1111111111111111111111111",
        },
        {
          name: "agent_wallet_program",
          address: "7onzUVc1HGc9oBDUspBdP8dz1QW6uXrSdBn4NH6aiLb",
        },
        {
          name: "token_program",
          address: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
        },
        {
          name: "system_program",
          address: "11111111111111111111111111111111",
        },
      ],
      args: [
        {
          name: "authorization",
          type: {
            defined: {
              name: "PaymentAuthorization",
            },
          },
        },
      ],
    },
    {
      name: "verify_receipt",
      docs: [
        "Read only check that the receipt for `authorization` exists and records exactly that",
        "payment. Fails with `AccountMismatch` when any field differs. Meant for simulation by a",
        "facilitator that wants the chain to confirm an earlier settlement.",
      ],
      discriminator: [202, 144, 21, 149, 181, 189, 23, 170],
      accounts: [
        {
          name: "receipt",
          pda: {
            seeds: [
              {
                kind: "const",
                value: [114, 101, 99, 101, 105, 112, 116],
              },
              {
                kind: "arg",
                path: "authorization.agent_wallet",
              },
              {
                kind: "arg",
                path: "authorization.nonce",
              },
            ],
          },
        },
      ],
      args: [
        {
          name: "authorization",
          type: {
            defined: {
              name: "PaymentAuthorization",
            },
          },
        },
      ],
    },
  ],
  accounts: [
    {
      name: "Receipt",
      discriminator: [39, 154, 73, 106, 80, 102, 145, 153],
    },
  ],
  events: [
    {
      name: "PaymentSettled",
      discriminator: [158, 182, 152, 76, 105, 23, 232, 135],
    },
  ],
  errors: [
    {
      code: 6100,
      name: "AuthorizationExpired",
      msg: "The payment authorization has expired. Ask the agent to sign a fresh one",
    },
    {
      code: 6101,
      name: "MissingSignatureVerification",
      msg: "The instruction before settle must be an Ed25519 signature check. Add it with ed25519VerifyInstruction",
    },
    {
      code: 6102,
      name: "SignatureMismatch",
      msg: "The Ed25519 check does not cover this authorization with its session key. Sign the exact authorization message",
    },
    {
      code: 6103,
      name: "NonceAlreadyUsed",
      msg: "This nonce has already settled. Use a new nonce for a new payment",
    },
    {
      code: 6104,
      name: "AccountMismatch",
      msg: "An account does not match the authorization. Pass the wallet, vault, mint and recipient it names",
    },
    {
      code: 6105,
      name: "RetentionNotElapsed",
      msg: "This receipt is still inside its retention period. Close it after 7 days past the authorization expiry",
    },
    {
      code: 6106,
      name: "NotFeePayer",
      msg: "Only the fee payer that paid for this receipt can close it. Sign with that key",
    },
  ],
  types: [
    {
      name: "AgentWallet",
      type: {
        kind: "struct",
        fields: [
          {
            name: "owner",
            type: "pubkey",
          },
          {
            name: "id",
            type: "u64",
          },
          {
            name: "mint",
            type: "pubkey",
          },
          {
            name: "vault",
            type: "pubkey",
          },
          {
            name: "bump",
            type: "u8",
          },
          {
            name: "vault_bump",
            type: "u8",
          },
          {
            name: "created_at",
            type: "i64",
          },
          {
            name: "per_call_cap",
            type: "u64",
          },
          {
            name: "daily_cap",
            type: "u64",
          },
          {
            name: "session_keys",
            type: {
              vec: {
                defined: {
                  name: "SessionKey",
                },
              },
            },
          },
          {
            name: "allow_list",
            type: {
              vec: {
                defined: {
                  name: "AllowListEntry",
                },
              },
            },
          },
          {
            name: "spend_buckets",
            docs: ["Ring of 97 buckets. The slot for bucket index `i` is `i mod 97`."],
            type: {
              vec: {
                defined: {
                  name: "SpendBucket",
                },
              },
            },
          },
          {
            name: "total_spent",
            type: "u64",
          },
          {
            name: "settlement_count",
            type: "u64",
          },
        ],
      },
    },
    {
      name: "AllowListEntry",
      type: {
        kind: "struct",
        fields: [
          {
            name: "resource_id",
            type: {
              array: ["u8", 32],
            },
          },
          {
            name: "recipient",
            docs: ["Owner of the recipient token account."],
            type: "pubkey",
          },
        ],
      },
    },
    {
      name: "PaymentAuthorization",
      docs: [
        "A payment the agent's session key agreed to. Borsh layout is the 208 byte body of the",
        "signed message and matches `encodeAuthorizationBody` in packages/shared.",
      ],
      type: {
        kind: "struct",
        fields: [
          {
            name: "agent_wallet",
            type: "pubkey",
          },
          {
            name: "session_key",
            type: "pubkey",
          },
          {
            name: "recipient",
            docs: ["Owner of the recipient token account."],
            type: "pubkey",
          },
          {
            name: "mint",
            type: "pubkey",
          },
          {
            name: "amount",
            docs: ["Base units of the mint."],
            type: "u64",
          },
          {
            name: "resource_id",
            type: {
              array: ["u8", 32],
            },
          },
          {
            name: "nonce",
            type: {
              array: ["u8", 32],
            },
          },
          {
            name: "expires_at",
            docs: ["Unix seconds."],
            type: "i64",
          },
        ],
      },
    },
    {
      name: "PaymentSettled",
      docs: [
        "Emitted with `emit!` so it lands in the program logs as `Program data: <base64>`.",
        "Carries every receipt field plus the receipt address.",
      ],
      type: {
        kind: "struct",
        fields: [
          {
            name: "receipt",
            type: "pubkey",
          },
          {
            name: "agent_wallet",
            type: "pubkey",
          },
          {
            name: "owner",
            type: "pubkey",
          },
          {
            name: "session_key",
            type: "pubkey",
          },
          {
            name: "recipient",
            type: "pubkey",
          },
          {
            name: "recipient_token",
            type: "pubkey",
          },
          {
            name: "mint",
            type: "pubkey",
          },
          {
            name: "amount",
            type: "u64",
          },
          {
            name: "resource_id",
            type: {
              array: ["u8", 32],
            },
          },
          {
            name: "nonce",
            type: {
              array: ["u8", 32],
            },
          },
          {
            name: "slot",
            type: "u64",
          },
          {
            name: "unix_timestamp",
            type: "i64",
          },
          {
            name: "fee_payer",
            type: "pubkey",
          },
          {
            name: "bump",
            type: "u8",
          },
          {
            name: "expires_at",
            docs: [
              "`expires_at` of the settled authorization. `close_receipt` waits until",
              "`RECEIPT_RETENTION_SECONDS` after it.",
            ],
            type: "i64",
          },
        ],
      },
    },
    {
      name: "Receipt",
      type: {
        kind: "struct",
        fields: [
          {
            name: "agent_wallet",
            type: "pubkey",
          },
          {
            name: "owner",
            type: "pubkey",
          },
          {
            name: "session_key",
            type: "pubkey",
          },
          {
            name: "recipient",
            type: "pubkey",
          },
          {
            name: "recipient_token",
            type: "pubkey",
          },
          {
            name: "mint",
            type: "pubkey",
          },
          {
            name: "amount",
            type: "u64",
          },
          {
            name: "resource_id",
            type: {
              array: ["u8", 32],
            },
          },
          {
            name: "nonce",
            type: {
              array: ["u8", 32],
            },
          },
          {
            name: "slot",
            type: "u64",
          },
          {
            name: "unix_timestamp",
            type: "i64",
          },
          {
            name: "fee_payer",
            type: "pubkey",
          },
          {
            name: "bump",
            type: "u8",
          },
          {
            name: "expires_at",
            docs: [
              "`expires_at` of the settled authorization. `close_receipt` waits until",
              "`RECEIPT_RETENTION_SECONDS` after it.",
            ],
            type: "i64",
          },
        ],
      },
    },
    {
      name: "SessionKey",
      type: {
        kind: "struct",
        fields: [
          {
            name: "key",
            type: "pubkey",
          },
          {
            name: "expires_at",
            docs: ["Unix seconds. 0 means no expiry."],
            type: "i64",
          },
          {
            name: "active",
            type: "bool",
          },
        ],
      },
    },
    {
      name: "SpendBucket",
      type: {
        kind: "struct",
        fields: [
          {
            name: "index",
            docs: ["`floor(unix_timestamp / 900)`."],
            type: "i64",
          },
          {
            name: "amount",
            type: "u64",
          },
        ],
      },
    },
  ],
  constants: [
    {
      name: "AUTHORIZATION_DOMAIN",
      docs: ["Domain prefix of every signed authorization. Exactly 20 ASCII bytes."],
      type: "bytes",
      value: "[84, 85, 82, 78, 83, 84, 73, 76, 69, 95, 80, 65, 89, 77, 69, 78, 84, 95, 86, 49]",
    },
    {
      name: "RECEIPT_RETENTION_SECONDS",
      docs: [
        "How long a receipt stays on chain after its authorization expires before the fee payer may",
        "close it and take the rent back. Seven days.",
      ],
      type: "i64",
      value: "604800",
    },
    {
      name: "SEED_RECEIPT",
      type: "bytes",
      value: "[114, 101, 99, 101, 105, 112, 116]",
    },
    {
      name: "SEED_SETTLEMENT_AUTHORITY",
      type: "bytes",
      value:
        "[115, 101, 116, 116, 108, 101, 109, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121]",
    },
  ],
} as const;
